# Generated by curation_concerns:models:install
class Collection < ActiveFedora::Base
  include ::CurationConcerns::CollectionBehavior
  # You can replace these metadata if they're not suitable
  include CurationConcerns::BasicMetadata
  include FedoraMigrate::LegacyMetadata
  include FedoraMigrate::BasicMetadata
end
