# Generated by curation_concerns:models:install
class Collection < ActiveFedora::Base
  include ::CurationConcerns::CollectionBehavior
  # You can replace these metadata if they're not suitable
  include CurationConcerns::BasicMetadata
  has_subresource "descMetadata", class_name: "ActiveFedora::File"
end
