# Generated by curation_concerns:models:install
class FileSet < ActiveFedora::Base
  include ::CurationConcerns::FileSetBehavior
  include FedoraMigrate::LegacyMetadata
  def viruses?
    false # no av installed on vagrant
  end
end
