# Generated by curation_concerns:models:install
class FileSet < ActiveFedora::Base
  include ::CurationConcerns::FileSetBehavior
  include FedoraMigrate::LegacyMetadata
  has_subresource "content", class_name: "ActiveFedora::File"
end
